### PR TITLE
Fix missing self in class Instance

### PR DESCRIPTION
**Pull request by TomSaw**
:D

### CODE REVIEW

**Review by salkinium — APPROVED** [review]
Ooops, thanks! Squash?

**Comment by TomSaw** [comment]
Fixed this in browser only. Could you squash pls !

**Comment by TomSaw** [comment]
... No clue if its less work for you doing so.
If the effort is the same, of course I'll squash it!

**Review by rleh — APPROVED** [review]

**Comment by rleh** [comment]
Squashed!

**Pull request merged**
